# costmap_common_params.yaml
plugins:
  - { name: static_layer,   type: "costmap_2d::StaticLayer" }
  - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
  - { name: inflation_layer,type: "costmap_2d::InflationLayer" }

static_layer:
  map_topic: /map
  subscribe_to_updates: true

obstacle_layer:
  observation_sources: base_scan
  base_scan:
    sensor_frame: base_scan
    data_type: LaserScan
    topic: /base_scan
    marking: true
    clearing: true

inflation_layer:
  inflation_radius: 0.2
  cost_scaling_factor: 1.0
