# global_costmap_params.yaml
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  static_map: true
  rolling_window: false
  update_frequency: 5.0
  publish_frequency: 2.0
  width: 20.0
  height: 20.0
  resolution: 0.05
