# local_costmap_params.yaml
local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  static_map: false
  rolling_window: true
  update_frequency: 5.0
  publish_frequency: 2.0
  width: 6.0
  height: 6.0
  resolution: 0.05
